/**
 * Build orchestrator: runs `astro build` and reports timing.
 * (Profile images are generated separately by the `build` script — see package.json.)
 * File: scripts/build.js
 */
import { execSync } from 'child_process';

console.log('🏗️ Building with Astro...');
const startTime = Date.now();

try {
    // The sitemap is generated by the @astrojs/sitemap integration during
    // `astro build` (sitemap-index.xml + sitemap-0.xml) — single source of truth.
    execSync('astro build', { stdio: 'inherit' });
} catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
}

const duration = ((Date.now() - startTime) / 1000).toFixed(2);
console.log(`✨ Build completed in ${duration}s`);
