/**
 * Unified script for the build process
 * Executes all necessary tasks in the correct order
 * File: scripts/build.js
 */

import { execSync } from 'child_process';

/**
 * Execute Astro build
 */
async function buildAstro() {
    console.log('🚀 Building with Astro...');

    try {
        execSync('astro build', { stdio: 'inherit' });
        console.log('✅ Build completed');
    } catch (error) {
        console.error('❌ Error during build:', error);
        process.exit(1);
    }
}

/**
 * Main function that executes the entire build process
 */
async function build() {
    console.log('🏗️ Starting build process...');

    const startTime = Date.now();

    try {
        // Execute tasks in sequence
        // NOTE: sitemap is generated by the @astrojs/sitemap integration during
        // `astro build` (sitemap-index.xml + sitemap-0.xml) — single source of truth
        await buildAstro();

        const duration = ((Date.now() - startTime) / 1000).toFixed(2);
        console.log(`✨ Build completed in ${duration}s`);
    } catch (error) {
        console.error('❌ Error in build process:', error);
        process.exit(1);
    }
}

// Execute main function
build();
