name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Prettier check
        run: npx prettier --check .
      - name: ESLint
        run: npm run lint
